### PR TITLE
Fixes and tweeks to match logic of Panic's original Cocoa source code.

### PR DESCRIPTION
**Pull request by miletbaker**
Hi, thanks for porting Panics code to coffee/js. I was having issues with your code not finding the same colours as Panic's OS X app and in some cases failing to find the text colours, so I implemented a few fixes detailed below:
- Changed threshold for selecting second choice background colour to be 30% used, from 40% to match Panic's original source. 
- Fixed issue with reversed logic on whether to find dark colour for text. 
- Fixed issue with reversed logic for selecting secondary text colour. 
- Fixed issue where colours were being passed for arrays when calling colour helper methods (now only colours are passed).
- Adjusted logic of final condition in isDistinct method to match Panic's logic (was using 1st colour for test rather than second). 
- Removed duplicate / redundant logic from isDistinct method. Recompiled app.js

I have tested it against the desktop app and am now getting exactly the same results.

Regards,

Jon

### CODE REVIEW

**Comment by lukasklein** [comment]
Hi miletbaker,
thanks a lot for your commit!
Though the contrast of the primary- secondary- and details color is much better it's still not the exact same colours as in Panic's version:
Screen Shot 2013-04-24 at 11 58 37 AM

Any ideas how this could be?

**Comment by miletbaker** [comment]
You are right, I didn't check with the Coldplay file. I think it is because the code is missing the minimum saturation check from the original code.

``` objc
- (NSColor*)pc_colorWithMinimumSaturation:(CGFloat)minSaturation
{
    NSColor *tempColor = [self colorUsingColorSpaceName:NSCalibratedRGBColorSpace];

    if ( tempColor != nil )
    {
        CGFloat hue = 0.0;
        CGFloat saturation = 0.0;
        CGFloat brightness = 0.0;
        CGFloat alpha = 0.0;

        [tempColor getHue:&hue saturation:&saturation brightness:&brightness alpha:&alpha];

        if ( saturation < minSaturation )
        {
            return [NSColor colorWithCalibratedHue:hue saturation:minSaturation brightness:brightness alpha:alpha];
        }
    }

    return self;
}
```

I'll take a look tonight or tomorrow at implementing this and see if it makes a difference.

Regards,

Jon

**Comment by miletbaker** [comment]
Looking into this further, I ran some debugs on both the original Panic code and your above and we seem to be getting different results when analysing the colour counts from the sample image.

Panics code gives the following:

2013-04-25 08:30:09.324 ColorArt[6186:303] 15: 147,160,176
2013-04-25 08:30:09.325 ColorArt[6186:303] 12: 151,164,181
2013-04-25 08:30:09.325 ColorArt[6186:303] 11: 154,166,182
2013-04-25 08:30:09.326 ColorArt[6186:303] 11: 156,170,183
2013-04-25 08:30:09.326 ColorArt[6186:303] 11: 141,154,170

(first value i.e. 15 is the count)

Where by your code is giving the following top 5:

15: 228,228,228 app.js:94
13: 147,160,176 app.js:94
13: 229,232,237 app.js:94
12: 83,134,197 app.js:94
12: 154,166,182 

I thought at first Panic's code was excluding colours if they were not saturated enough, but looking at the code above all it does is increase the saturation of those that are not saturated enough so I am not sure to be honest.

**Comment by miletbaker** [comment]
I've added another commit as I have found another issue. If you have more than one function call without parenthesis in a condition, coffeescript miss interprets this and passed the condition statement to the first function call. This was happening with the text selection logic.

We still get different colours from the Cocoa app but as per my comment above we get a different result on the colour counts. I am not sure if this is due to differences in how Javascript and Objective-C get colours or if we have other code issues. I have not had a chance to check if there are other function based conditions that need parenthesis for example.

**Pull request merged**
